var seven;
(function (seven) {
    class DefaultWindowLoader {
        getClassName() { return seven.DefaultWindowLoader.classname; }
        loadIfDefault() {
            if (seven.JBDocument.document().hasWindowLoader() == false) {
                seven.Logger.boot("no window loader found -- using default");
                seven.JBDocument.document().setWindowLoader(this);
            }
        }
        setup(document) {
            this.document = document;
        }
        loadWindows(sizeClass) {
            var window = new seven.CanvasWindow().initWithId('main', new seven.Rect(0, 0, 1000, 800), new seven.ViewController());
            this.document.addSubWindow(window);
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    DefaultWindowLoader.classname = "seven.DefaultWindowLoader";
    seven.DefaultWindowLoader = DefaultWindowLoader;
})(seven || (seven = {}));
