namespace seven {
    export class ImageLoadedCallback {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.ImageLoadedCallback";
		public getClassName():string{return ImageLoadedCallback.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
    thisRef: Object;
    method: (image: HTMLImageElement) => void;
    public constructor(thisRef: Object, method: (image: HTMLImageElement) => void) {
        this.thisRef = thisRef;
        this.method = method;
    }
    call(image:HTMLImageElement) {
        this.method.call(this.thisRef,image);
    }
}
}