namespace seven {
    export class UserAgent {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.UserAgent";
		public getClassName():string{return UserAgent.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        private static _instance;
        public static userAgent(): ClassLoader {
            if (UserAgent._instance == undefined) {
                UserAgent._instance = new ClassLoader();
            }
            return UserAgent._instance;
        }


        public hasTouchScreen():boolean{
            return (('ontouchstart' in window) || (navigator.msMaxTouchPoints > 0));            
        }
        
    }

}
