var seven;
(function (seven) {
    class SizeNotifier {
        /* private */ constructor() {
            this.observers = {};
        }
        getClassName() { return seven.SizeNotifier.classname; }
        static notifier() {
            if (SizeNotifier._notifier == undefined) {
                SizeNotifier._notifier = new SizeNotifier();
            }
            return SizeNotifier._notifier;
        }
        addResizeHandler(handler) {
            if (this.observers[SizeNotifyOptions.SIZE_CLASS_CHANGE] == undefined) {
                this.observers[SizeNotifyOptions.SIZE_CLASS_CHANGE] = new Array();
            }
            var observerArray = this.observers[SizeNotifyOptions.SIZE_CLASS_CHANGE];
            var found = false;
            for (let everyObserver of observerArray) {
                if (everyObserver == handler) {
                    found = true;
                }
            }
            if (found == false) {
                observerArray.push(handler);
            }
            this.observers[SizeNotifyOptions.SIZE_CLASS_CHANGE] = observerArray;
        }
        postSizeClassChange(fromClass, toClass) {
            seven.Objects.requireNonNull("", fromClass);
            seven.Objects.requireNonNull("", toClass);
            for (var counter in this.observers[SizeNotifyOptions.SIZE_CLASS_CHANGE]) {
                var handler = this.observers[SizeNotifyOptions.SIZE_CLASS_CHANGE][counter];
                //call the observer method with userInfo 
                handler.handleSizeClassChange(fromClass, toClass);
            }
        }
        removeSizeClassChangeHandler(observerThis) {
            for (var counter in this.observers[SizeNotifyOptions.SIZE_CLASS_CHANGE]) {
                var observer = this.observers[SizeNotifyOptions.SIZE_CLASS_CHANGE][counter];
                //call the observer method with userInfo 
                if (observer.thisRef == observerThis) {
                    delete this.observers[SizeNotifyOptions.SIZE_CLASS_CHANGE][counter];
                }
            }
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    SizeNotifier.classname = "seven.SizeNotifier ";
    seven.SizeNotifier = SizeNotifier;
    let SizeNotifyOptions;
    (function (SizeNotifyOptions) {
        SizeNotifyOptions[SizeNotifyOptions["NONE"] = 0] = "NONE";
        SizeNotifyOptions[SizeNotifyOptions["SIZE_CLASS_CHANGE"] = 1] = "SIZE_CLASS_CHANGE";
    })(SizeNotifyOptions || (SizeNotifyOptions = {}));
})(seven || (seven = {}));
