//{INSERTORDER:3}

namespace seven {
    export class ClickGestureCallback extends GestureCallback {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.ClickGestureCallback";
		public getClassName():string{return ClickGestureCallback.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        public constructor() {
            super();

        }
        private static keyGenerator = new ClickGestureCallback();
        public static keyOf(values: JMBMap<string, any>) {
            return ClickGestureCallback.keyGenerator.getKey();
        }

        getKey(): string {
            return "" + GestureType.Click;
        }
        getType(): GestureType {
            return GestureType.Click;
        }
        public copyAttributes(toObject: ClickGestureCallback): void {
            super.copyAttributes(toObject);
        }
        public copy(): ClickGestureCallback {
            var newObject: ClickGestureCallback = new ClickGestureCallback();
            this.copyAttributes(newObject);
            return newObject;
        }
    }
}
