var seven;
(function (seven) {
    class UniqueKeyEnumation {
        constructor() {
            this.keys = new Array();
        }
        getClassName() { return seven.UniqueKeyEnumation.classname; }
        hasKey(key) {
            var hasKey = 0;
            this.keys.forEach(element => {
                if (element == key) {
                    hasKey = 1;
                }
            });
            if (hasKey == 1) {
                return true;
            }
            return false;
        }
        addKey(key) {
            var hasKey = 0;
            this.keys.forEach(element => {
                if (element == key) {
                    hasKey = 1;
                }
            });
            if (hasKey == 1) {
                throw new Error("UniqueKeyEnumation - tried to add duplicate key");
            }
            this.keys.push(key);
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    UniqueKeyEnumation.classname = "seven.UniqueKeyEnumation ";
    seven.UniqueKeyEnumation = UniqueKeyEnumation;
})(seven || (seven = {}));
