//{INSERTORDER:3}

namespace seven {


    export class CanvasWindow extends JMBWindow {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.CanvasWindow";
		public getClassName():string{return CanvasWindow.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        view: HtmlCanvasView;

        public static new(canvasID: string, rect: IRect,controller:ViewController = new ViewController()):CanvasWindow {
            return new CanvasWindow().initWithId(canvasID, rect,controller);
        }

        constructor() {
            super();
        }

        initWithId(htmlId: string, rect: IRect,controller:ViewController): CanvasWindow {
            super.init(htmlId,controller);
            this.controller.view = new HtmlCanvasView(this.htmlElementId).initWitFrame(rect);
            this.view = <HtmlCanvasView>this.controller.view;
            return this;
        }

        setupView() {
            this.view = new HtmlCanvasView(this.htmlElementId);
        }

        remove() {
            this.view.remove();
        }
    }
}