//{INSERTORDER:2}

namespace seven {
    export abstract class JMBWindow extends JBObject implements IWindow {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.JMBWindow";
		public getClassName():string{return JMBWindow.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
    view: View;
    controller: ViewController;
    htmlElementId: string;
    htmlElement: HTMLElement;
  

    constructor() {
        super()
    }

    protected init(htmlId: string,controller:ViewController = new ViewController()) :JMBWindow{
        this.htmlElementId = htmlId;
        this.htmlElement = document.getElementById(htmlId);
        this.controller = controller;
        Object.freeze(this.htmlElement);
        return this;
    }



    setupTouches() {
    }
    
    getController(): ViewController {
        return this.controller;
    }

    hasMovedToWindowController(controller: ViewController) {
        this.controller = controller;
    }


}
}