namespace seven {
    export
        class SizeLoadOption {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.SizeLoadOption";
		public getClassName():string{return SizeLoadOption.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        isMobileDevice(): boolean {
            if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
                return true;
            }
            return false;
        }
        isDesktop(): boolean {
            if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
                return false;
            }
            return true;
        }
    }
}