
namespace seven {
    export class UserInfo{
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.UserInfo";
		public getClassName():string{return UserInfo.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
    public static clientInfo():SizeLoadOption{
        return new SizeLoadOption();
    }
}
}