var storyboard;
(function (storyboard) {
    class FileLoader {
        constructor() {
        }
        getClassName() { return storyboard.FileLoader.classname; }
        load() {
            try {
                var storyboardAdapter = storyboard.SevenAdapter.shared().storyboardAdapter;
                var documentEl = this.document.getElementsByTagName("document")[0];
                var deviceEl = documentEl.getElementsByTagName("device")[0];
                var adaptationsEl = deviceEl.getElementsByTagName("adaptation");
                var scenesEl = documentEl.getElementsByTagName("scenes")[0];
                var scenesEntriesEl = scenesEl.getElementsByTagName("scene");
                storyboardAdapter.document = storyboard.Document.fromXML(documentEl);
                storyboard.SevenAdapter.shared().registerForObjectID(storyboardAdapter.document.initialViewController.id, storyboardAdapter.document);
                storyboardAdapter.document.device = storyboard.Device.fromXML(deviceEl);
                for (const adaptationEl of adaptationsEl) {
                    var adaptation = storyboard.Adaptation.fromXML(adaptationEl);
                    storyboardAdapter.document.device.adaptations.push(adaptation);
                }
                for (const scenesEntryEl of scenesEntriesEl) {
                    this.loadScene(scenesEntryEl);
                }
            }
            catch (e) {
                console.error(e);
            }
        }
        loadScene(sceneEL) {
            var scene = storyboard.Scene.fromXML(sceneEL);
            var objects = sceneEL.getElementsByTagName("objects")[0];
            for (let object of objects.children) {
                if (object.nodeName == "viewController") {
                    scene.objects.push(this.loadViewController(object, scene));
                }
            }
            storyboard.SevenAdapter.shared().storyboardAdapter.scenes.push(scene);
        }
        loadViewController(element, scene) {
            var viewController = storyboard.ViewController.fromXML(element);
            viewController.scene = scene;
            viewController.view = this.loadView(element.getElementsByTagName("view")[0]);
            storyboard.SevenAdapter.shared().hasLoadedObject(viewController);
            return viewController;
        }
        loadView(viewEl) {
            var rectEl = viewEl.getElementsByTagName("rect")[0];
            var view = storyboard.View.fromXML(viewEl);
            view.rect = storyboard.Rect.fromXML(rectEl);
            var subviewsEl = viewEl.getElementsByTagName("subviews")[0];
            for (let subviewEl of subviewsEl.children) {
                this.addSubView(view, subviewEl);
            }
            return view;
        }
        addSubView(parent, subView) {
            if (subView.nodeName == "textField") {
                parent.subViews.push(storyboard.TextField.fromXML(subView));
            }
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    FileLoader.classname = "storyboard.FileLoader ";
    storyboard.FileLoader = FileLoader;
})(storyboard || (storyboard = {}));
