var storyboard;
(function (storyboard) {
    class Renderer {
        getClassName() { return storyboard.Renderer.classname; }
        ///AutoGeneratedClassName-end - do not eidt this line
        renderViewHierachy(superView) {
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Renderer.classname = "storyboard.Renderer";
    storyboard.Renderer = Renderer;
})(storyboard || (storyboard = {}));
