var storyboard;
(function (storyboard) {
    class SevenAdapter {
        constructor() {
            this.registry = {};
            this.loadedObjects = {};
        }
        getClassName() { return storyboard.SevenAdapter.classname; }
        static shared() {
            if (SevenAdapter._instance == undefined) {
                var inst = SevenAdapter._instance = new SevenAdapter();
                inst.storyboardAdapter = new storyboard.StoryboardSideAdapter();
            }
            return SevenAdapter._instance;
        }
        getObjectForId(id) {
            return this.loadedObjects[id];
        }
        registerForObjectID(id, callback) {
            if (this.registry[id] == undefined) {
                this.registry[id] = new Array();
            }
            this.registry[id].push(callback);
        }
        hasLoadedObject(object) {
            this.loadedObjects[object.id] = object;
            if (this.registry[object.id] == undefined) {
                return;
            }
            for (let callback of this.registry[object.id]) {
                callback.hasLoadedObject(object.id, object);
            }
        }
        getInitialScene() {
            return this.storyboardAdapter.document.initialViewController.scene;
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    SevenAdapter.classname = "storyboard.SevenAdapter ";
    storyboard.SevenAdapter = SevenAdapter;
})(storyboard || (storyboard = {}));
