var storyboard;
(function (storyboard) {
    class SizeLoader {
        constructor() {
            this.deviceSize = new DeviceSize();
        }
        getClassName() { return storyboard.SizeLoader.classname; }
        initWithDevice(device) {
            this.sizeCatalog = this.deviceSize.getSize(device);
            seven.JBDocument.document().setSizeLoader(this);
        }
        initWithOptions(options) {
        }
        getBaseClass() {
            return this.sizeCatalog.getBaseClass();
        }
        changeSizeClass(width, height) {
            this.sizeCatalog.changeForSize(width, height);
        }
        getSizeClass() {
            return this.sizeCatalog.getSizeClass();
        }
        toString() {
            return "<storyboard.SizeLoader>";
        }
        getSizeRectForKey(key) {
            throw new Error("Method not implemented.");
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    SizeLoader.classname = "storyboard.SizeLoader";
    storyboard.SizeLoader = SizeLoader;
    class DeviceSize {
        constructor() {
            this.ipad9_7 = new seven.SizeCatalog("ipad9_7");
            this.ipad9_7.addSizeClasses([
                new seven.SizeClass("portrait", 768, 1024, ""),
                new seven.SizeClass("landscape", 1024, 768, "")
            ]);
        }
        getSize(device) {
            if (device.id == "ipad9_7") {
                this.ipad9_7.setBaseClassById(device.orientation);
                return this.ipad9_7;
            }
            throw new Error("no size for device : " + device.id);
        }
    }
    storyboard.DeviceSize = DeviceSize;
})(storyboard || (storyboard = {}));
