var storyboard;
(function (storyboard) {
    class StoryboardSideAdapter {
        constructor() {
            this.scenes = new Array();
        }
        getClassName() { return storyboard.StoryboardSideAdapter.classname; }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    StoryboardSideAdapter.classname = "storyboard.StoryboardSideAdapter";
    storyboard.StoryboardSideAdapter = StoryboardSideAdapter;
})(storyboard || (storyboard = {}));
