var storyboard;
(function (storyboard) {
    class WindowLoader {
        constructor() {
            ///AutoGeneratedClassName-end - do not eidt this line
            this.windows = new Array();
        }
        getClassName() { return storyboard.WindowLoader.classname; }
        setup(document) {
            var scene = storyboard.SevenAdapter.shared().getInitialScene();
            for (let object of scene.objects) {
                if (object.getClassName() == "storyboard.ViewController") {
                    this.addWindowController(object);
                }
            }
            for (let window of this.windows) {
                seven.JBDocument.document().addSubWindow(window);
            }
        }
        loadWindows(sizeClass) {
        }
        addWindowController(controller) {
            var style = storyboard.SevenAdapter.shared().getObjectForId(controller.view.id);
            seven.Objects.requireNonNull("StyleProder must not be null", style);
            var window = seven.CanvasWindow.new(controller.view.id, controller.view.rect);
            this.windows.push(window);
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    WindowLoader.classname = "storyboard.WindowLoader";
    storyboard.WindowLoader = WindowLoader;
})(storyboard || (storyboard = {}));
