namespace storyboard{
    export class Constraint {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.Constraint";
		public getClassName():string{return Constraint.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
       firstItem:string;
       firstAttribute:string;
       secoundItem:string;
       secoundAttribute:string;
       multiplier:number;
       constant:number;
       id:string;
    }
}