//{INSERTORDER:2}

namespace seven {
    
        export class TouchInterpreterConfiguration extends JBObject {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.TouchInterpreterConfiguration";
		public getClassName():string{return TouchInterpreterConfiguration.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
            constructor() {
                super();
            }
        }
    }