var seven;
(function (seven) {
    class JMBIterator {
        constructor(arr) {
            this.index = 0;
            this.inputArray = arr;
        }
        getClassName() { return seven.JMBIterator.classname; }
        hasNext() {
            return this.index < this.inputArray.length;
        }
        next() {
            if (this.hasNext() == false) {
                return undefined;
            }
            var nextElement = this.inputArray[this.index];
            this.index++;
            return nextElement;
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    JMBIterator.classname = "seven.JMBIterator";
    seven.JMBIterator = JMBIterator;
})(seven || (seven = {}));
