//{INSERTORDER:1}
var seven;
(function (seven) {
    class JBObject {
        constructor() {
            this.className = this.constructor.name;
            seven.ClassLoader.manager().hasLoaded(this.getClassName());
        }
        getClassName() {
            if (this.className == undefined) {
                seven.Logger.error("classname was not defined");
            }
            return this.className;
        }
        equals(object) {
            if (object == undefined) {
                return false;
            }
            return object == this;
        }
        hasBeenLoaded() {
        }
        hashcode() {
            return 0;
        }
        toString() {
            return this.className;
        }
        copyAttributes(toObject) {
            toObject.className = this.className;
        }
        copy() {
            var newObject = new JBObject();
            this.copyAttributes(newObject);
            return newObject;
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    JBObject.classname = "seven.JBObject";
    seven.JBObject = JBObject;
})(seven || (seven = {}));
