var seven;
(function (seven) {
    class CookieManager {
        getClassName() { return seven.CookieManager.classname; }
        ///AutoGeneratedClassName-end - do not eidt this line
        setCookie(name, value, expireHours) {
            try {
                localStorage.setItem(name, value);
            }
            catch (e) {
                var d = new Date();
                d.setTime(d.getTime() + (expireHours * 60 * 60 * 1000));
                var expires = "expires=" + d.toUTCString();
                document.cookie = name + "=" + value + "; " + expires;
            }
        }
        getCookie(name) {
            try {
                return localStorage.getItem(name);
            }
            catch (e) {
                name = name + "=";
                var ca = document.cookie.split(';');
                for (var i = 0; i < ca.length; i++) {
                    var c = ca[i];
                    while (c.charAt(0) == ' ') {
                        c = c.substring(1);
                    }
                    if (c.indexOf(name) == 0) {
                        return c.substring(name.length, c.length);
                    }
                }
            }
            return "";
        }
        getCookieStartWithNeedle(name) {
            var allCookies = new seven.JMBMap();
            try {
                for (var info in window.localStorage) {
                    if (info.indexOf(name) == 0) {
                        allCookies.put(info, this.getCookie(info));
                    }
                }
            }
            catch (e) {
                var ca = document.cookie.split(';');
                for (var i = 0; i < ca.length; i++) {
                    var c = ca[i];
                    while (c.charAt(0) == ' ') {
                        c = c.substring(1);
                    }
                    if (c.indexOf(name) == 0) {
                        var index = c.indexOf("=");
                        var key = c.substring(0, index);
                        allCookies.put(key, c.substring(key.length + 1, c.length));
                    }
                }
            }
            return allCookies;
        }
        getCookieArrayStartWithNeedle(name) {
            var allCookies = new Array();
            try {
                for (var info in window.localStorage) {
                    if (info.indexOf(name) == 0) {
                        allCookies.push(this.getCookie(info));
                    }
                }
            }
            catch (e) {
                var ca = document.cookie.split(';');
                for (var i = 0; i < ca.length; i++) {
                    var c = ca[i];
                    while (c.charAt(0) == ' ') {
                        c = c.substring(1);
                    }
                    if (c.indexOf(name) == 0) {
                        var index = c.indexOf("=");
                        var key = c.substring(0, index);
                        allCookies.push(c.substring(key.length + 1, c.length));
                    }
                }
            }
            return allCookies;
        }
        deleteCookie(name) {
            try {
                localStorage.removeItem(name);
            }
            catch (e) {
                document.cookie = name + '=; expires=Thu, 01 Jan 1970 00:00:01 GMT;';
            }
        }
        deleteAllCookiesWithNeedle(needle) {
            var cookies = this.getCookieStartWithNeedle(needle);
            for (let cookie of cookies.keys()) {
                this.deleteCookie(cookie);
            }
        }
        deleteAllCookies() {
            try {
                window.localStorage.clear();
            }
            catch (e) {
                document.cookie.split(";").forEach(function (c) { document.cookie = c.replace(/^ +/, "").replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/"); });
            }
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    CookieManager.classname = "seven.CookieManager ";
    seven.CookieManager = CookieManager;
})(seven || (seven = {}));
