//{INSERTORDER:2}


namespace seven {
    export class Color {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.Color";
		public getClassName():string{return Color.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
    public static transparent(): string {
        return "rgba(0,0,0,0.0)";
    }

}
}