
namespace seven{
    export class Timer{
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.Timer";
		public getClassName():string{return Timer.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        private timeoutTimer:any = undefined;
        private timeoutCallback:VoidCallback;
    
        timeout(time:number,callback:VoidCallback){
            this.timeoutCallback = callback;
           
            this.stop(); 
            var that = this;
            this.timeoutTimer = setTimeout(function(){
                that.timeoutCalled();
            },time);
        }
    
        timeoutCalled(){
            console.log("called");
            this.stop();
            this.timeoutCallback.call();
            
        }
    
    
        interval(time:number,cllback:VoidCallback){}
        stop(){
            clearTimeout(this.timeoutTimer);
            this.timeoutTimer = undefined;
        }
    }
}
