namespace seven {
    export class ViewUtility {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.ViewUtility";
		public getClassName():string{return ViewUtility.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
    constructor(){
    }
    public static randomColor(){

     return '#' + this.hex(this.rg(1, 10)) + this.hex(this.rg(1, 10)) + this.hex(this.rg(1, 15)) +
         this.hex(this.rg(1, 15)) + this.hex(this.rg(1, 15)) + this.hex(this.rg(1, 15));
    }

    public static rg(m, n) {
        return Math.floor(Math.random() * (n - m + 1)) + m;
    }

    public static hex(i) {
        return i.toString(16);
    }
}
}