
//{INSERTORDER:2}
namespace seven{
    export abstract class TouchIntepreter extends JBObject{
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.TouchIntepreter";
		public getClassName():string{return TouchIntepreter.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        delegate:ITouchIntepreterDelegate;
        constructor(){
            super();
        }
        public setDelegate(delegate:ITouchIntepreterDelegate):void{
            this.delegate = delegate;
        }
    
    }
}
