var seven;
(function (seven) {
    class DefaultStyleProvider {
        constructor() {
            ///AutoGeneratedClassName-end - do not eidt this line
            this.backgroundColor = "white";
            this.strokeColor = "black";
        }
        getClassName() { return seven.DefaultStyleProvider.classname; }
        setBackgroundColor(color) {
            this.backgroundColor = color;
        }
        getBackGroundColor() {
            return this.backgroundColor;
        }
        isHidden() {
            return this.hide;
        }
        setHidden(hide) {
            this.hide = hide;
        }
        getStrokeColor() {
            return this.strokeColor;
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    DefaultStyleProvider.classname = "seven.DefaultStyleProvider";
    seven.DefaultStyleProvider = DefaultStyleProvider;
})(seven || (seven = {}));
