namespace seven{
    export class DefaultRenderer implements IRenderer{
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.DefaultRenderer";
		public getClassName():string{return DefaultRenderer.classname;}
		//AutoGeneratedClassName-end - do not eidt this line

        loadIfDefault() {
            if (JBDocument.document().hasRenderer() == false) {
                Logger.boot("no renderer found -- using default");
                    JBDocument.document().setRenderer(this);
            }
        }

        renderViewHierachy(superView: View) {
            for (let subView of superView.getSubViews()) {
                subView.drawInRect(subView.frame);
                this.drawSubView(subView);
            }
        }

        drawSubView(view:View){
            for (let subView of view.getSubViews()) {
                subView.drawInRect(subView.frame);
                this.drawSubView(subView);
            }
        }

    }
}