namespace seven{
    export class DefaultStyleProvider implements IStyleProdiver{
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.DefaultStyleProvider";
		public getClassName():string{return DefaultStyleProvider.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        private backgroundColor = "white";
        private strokeColor = "black";
        private hide:boolean;

        setBackgroundColor(color: string) {
           this.backgroundColor = color;
        }       
         getBackGroundColor(): string {
           return this.backgroundColor;
        }
        isHidden(): boolean {
           return this.hide;
        }
        setHidden(hide: boolean) {
         this.hide = hide;
        }
        getStrokeColor(): string {
           return this.strokeColor;
        }

       
    }
}