namespace seven {
    export class DefaultWindowLoader implements IWindowLoader {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.DefaultWindowLoader";
		public getClassName():string{return DefaultWindowLoader.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        document: JBDocument;

        loadIfDefault() {
            if (JBDocument.document().hasWindowLoader() == false) {
                Logger.boot("no window loader found -- using default");
                    JBDocument.document().setWindowLoader(this);
            }
        }
        setup(document: JBDocument) {
            this.document = document;
        }

        loadWindows(sizeClass: ISizeClass) {
            var window = new CanvasWindow().initWithId('main',new Rect(0,0,1000,800),new ViewController());
            this.document.addSubWindow(window);
        }


    }
}
