var seven;
(function (seven) {
    class Observer {
        constructor(thisRef, method, userInfo) {
            this.thisRef = thisRef;
            this.method = method;
            this.userInfo = userInfo;
        }
        getClassName() { return seven.Observer.classname; }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Observer.classname = "seven.Observer";
    seven.Observer = Observer;
})(seven || (seven = {}));
