
namespace storyboard{
    export class ActivityIndicationView extends Object {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.ActivityIndicationView";
		public getClassName():string{return ActivityIndicationView.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        key:string;
        contentMode:string;
        subViews:Array<Object>;
    }
}