namespace storyboard{
    export class Adaptation {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.Adaptation";
		public getClassName():string{return Adaptation.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        id:string;

        public static fromXML(xml: Element): Adaptation {
            var adaptation = new Adaptation();
            adaptation.id = xml.getAttribute("id");
            return adaptation;
        }
    }
}