namespace storyboard{
    export class Color {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.Color";
		public getClassName():string{return Color.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        key:string;
        red:number;
        green:number;
        blue:number;
        alpha:number;
        colorSpace:string;
        customColorSpace:string;
    }
}