namespace storyboard{
    export class Device {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.Device";
		public getClassName():string{return Device.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        id:string;
        orientation:string;
        adaptations:Array<Adaptation> = new Array();

        public static fromXML(xml: Element): Device {
            var device = new Device();
            device.id = xml.getAttribute("id");
            device.orientation = xml.getAttribute("orientation");
            return device;
        }
    }
    
}