namespace storyboard {
    export class PlaceHolder {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.PlaceHolder";
		public getClassName():string{return PlaceHolder.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        placeHolderIdentifier: string;
        id: string;
        sceneMemberID:string;
    }
}