namespace storyboard {
    export class Point {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.Point";
		public getClassName():string{return Point.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
       key:string;
       x:number;
       y:number;
    }
}