
namespace storyboard{
    export class ProgressView extends Object {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.ProgressView";
		public getClassName():string{return ProgressView.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        key:string;
        contentMode:string;
    }
}