
namespace storyboard{
    export class Rect implements seven.IRect {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.Rect";
		public getClassName():string{return Rect.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        public x() {
            return this._x;
        }
        public y() {
            return this._y;
        }
       
        public width() {
            return this._width;
        }
        public height() {
            return this._height;
        }
        key:string;
        _x:number;
        _y:number;
        _width:number;
        _height:number;

        public static fromXML(xml: Element): Rect {
            var rect = new Rect();
            rect.key = xml.getAttribute("key");
            rect._x = parseInt(xml.getAttribute("x"));
            rect._y = parseInt(xml.getAttribute("y"));
            rect._width = parseInt(xml.getAttribute("width"));
            rect._height = parseInt(xml.getAttribute("height"));
            return rect;
        }
    }
}