namespace storyboard{
    export class Scene {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.Scene";
		public getClassName():string{return Scene.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        sceneID:string;
        objects:Array<Object> = new Array();

        public static fromXML(xml: Element): Scene {
            var scene = new Scene();
            scene.sceneID = xml.getAttribute("sceneID");
            return scene;
        }

    }
}