
namespace storyboard{
    export class SegmentedControl extends Object {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.SegmentedControl";
		public getClassName():string{return SegmentedControl.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        key:string;
        contentMode:string;
    }
}