
namespace storyboard{
    export class Slider extends Object {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.Slider";
		public getClassName():string{return Slider.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        key:string;
        contentMode:string;
    }
}