namespace storyboard{
    export class ViewLayoutGuide {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.ViewLayoutGuide";
		public getClassName():string{return ViewLayoutGuide.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        key:string;
        id:string;
    }
}
