
namespace storyboard{
    export class View extends Object implements seven.IStyleProdiver{
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.View";
		public getClassName():string{return View.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        setBackgroundColor(color: string) {
            
        }
        getBackGroundColor(): string {
          return "red";
        }
        isHidden(): boolean {
            return false;
        }
        setHidden(hide: boolean) {
        }
        getStrokeColor(): string {
            return "black";
        }
        key:string;
        color:Color;
        contentMode:string;
        private rect:Rect;
        subViews:Array<Object> = new Array();
        constraits:Array<Constraint> = new Array();

        public static fromXML(xml: Element): View {
            var view = new View();
            view.id = xml.getAttribute("id");
            view.key = xml.getAttribute("key");
            view.contentMode = xml.getAttribute("contentMode");
            return view;
        }

        public getRect():Rect{
            return this.rect;
        }
        public setRect(rect:Rect):Rect{
            return this.rect = rect;
        }
    }
}