//{INSERTORDER:3}

namespace seven {
    export class DocumentController extends AbstractViewController {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.DocumentController";
		public getClassName():string{return DocumentController.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        view: DocumentView;

        constructor() {
            super();
        }
    }
}