//{INSERTORDER:3}

namespace seven {
    export class ViewController extends AbstractViewController {
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.ViewController";
		public getClassName():string{return ViewController.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
    childViewController: Array<AbstractViewController>;

    constructor() {
        super();
        
    }
    public documentController(): DocumentController {
        Objects.requireNonNull("ViewController.docuemntController : tried to access nonnull value", JBDocument.document().documentController);
        return JBDocument.document().documentController;
    }
  
    public setParentViewController(viewController: ViewController): void {
        this.parentViewController = viewController;
       
    }

}
}