var seven;
(function (seven) {
    class UserInfo {
        getClassName() { return seven.UserInfo.classname; }
        ///AutoGeneratedClassName-end - do not eidt this line
        static clientInfo() {
            return new seven.SizeLoadOption();
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    UserInfo.classname = "seven.UserInfo";
    seven.UserInfo = UserInfo;
})(seven || (seven = {}));
