var storyboard;
(function (storyboard) {
    class Adaptation {
        getClassName() { return storyboard.Adaptation.classname; }
        static fromXML(xml) {
            var adaptation = new Adaptation();
            adaptation.id = xml.getAttribute("id");
            return adaptation;
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Adaptation.classname = "storyboard.Adaptation ";
    storyboard.Adaptation = Adaptation;
})(storyboard || (storyboard = {}));
