var storyboard;
(function (storyboard) {
    class AutoResizeMask {
        getClassName() { return storyboard.AutoResizeMask.classname; }
        static fromXML(xml) {
            var resizeMask = new AutoResizeMask();
            resizeMask.id = xml.getAttribute("id");
            resizeMask.key = xml.getAttribute("key");
            resizeMask.withSizable = storyboard.toBoolean(xml.getAttribute("withSizable"));
            resizeMask.heightSizable = storyboard.toBoolean(xml.getAttribute("heightSizable"));
            return resizeMask;
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    AutoResizeMask.classname = "storyboard.AutoResizeMask ";
    storyboard.AutoResizeMask = AutoResizeMask;
})(storyboard || (storyboard = {}));
