var storyboard;
(function (storyboard) {
    class Color {
        getClassName() { return storyboard.Color.classname; }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Color.classname = "storyboard.Color ";
    storyboard.Color = Color;
})(storyboard || (storyboard = {}));
