var storyboard;
(function (storyboard) {
    class Document {
        constructor() {
            this.scenes = new Array();
        }
        getClassName() { return storyboard.Document.classname; }
        static fromXML(xml) {
            var document = new Document();
            document.type = xml.getAttribute("type");
            document.version = xml.getAttribute("version");
            document.toolsVersion = xml.getAttribute("toolsversion");
            document.targetRuntime = xml.getAttribute("targetRuntime");
            document.propertyAccessControl = xml.getAttribute("propertyAccessControl");
            document.useAutolayout = storyboard.toBoolean(xml.getAttribute("useAutolayout"));
            document.useTraitCollections = storyboard.toBoolean(xml.getAttribute("useTraitCollections"));
            document.useSafeAreas = storyboard.toBoolean(xml.getAttribute("useSafeAreas"));
            document.colorMatched = storyboard.toBoolean(xml.getAttribute("colorMatched"));
            document.initialViewController = storyboard.Object.unmodifiable(xml.getAttribute("initialViewController"), undefined);
            return document;
        }
        hasLoadedObject(id, object) {
            if (id == this.initialViewController.id) {
                this.initialViewController = object;
            }
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Document.classname = "storyboard.Document";
    storyboard.Document = Document;
})(storyboard || (storyboard = {}));
