var storyboard;
(function (storyboard) {
    class PlaceHolder {
        getClassName() { return storyboard.PlaceHolder.classname; }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    PlaceHolder.classname = "storyboard.PlaceHolder ";
    storyboard.PlaceHolder = PlaceHolder;
})(storyboard || (storyboard = {}));
