var storyboard;
(function (storyboard) {
    class Point {
        getClassName() { return storyboard.Point.classname; }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Point.classname = "storyboard.Point ";
    storyboard.Point = Point;
})(storyboard || (storyboard = {}));
