var storyboard;
(function (storyboard) {
    class Rect {
        getClassName() { return storyboard.Rect.classname; }
        ///AutoGeneratedClassName-end - do not eidt this line
        x() {
            return this._x;
        }
        y() {
            return this._y;
        }
        width() {
            return this._width;
        }
        height() {
            return this._height;
        }
        static fromXML(xml) {
            var rect = new Rect();
            rect.key = xml.getAttribute("key");
            rect._x = parseInt(xml.getAttribute("x"));
            rect._y = parseInt(xml.getAttribute("y"));
            rect._width = parseInt(xml.getAttribute("width"));
            rect._height = parseInt(xml.getAttribute("height"));
            return rect;
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Rect.classname = "storyboard.Rect";
    storyboard.Rect = Rect;
})(storyboard || (storyboard = {}));
