var storyboard;
(function (storyboard) {
    class Scene {
        constructor() {
            this.objects = new Array();
        }
        getClassName() { return storyboard.Scene.classname; }
        static fromXML(xml) {
            var scene = new Scene();
            scene.sceneID = xml.getAttribute("sceneID");
            return scene;
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Scene.classname = "storyboard.Scene ";
    storyboard.Scene = Scene;
})(storyboard || (storyboard = {}));
