var storyboard;
(function (storyboard) {
    class Variation {
        getClassName() { return storyboard.Variation.classname; }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Variation.classname = "storyboard.Variation ";
    storyboard.Variation = Variation;
    class Mask {
    }
    storyboard.Mask = Mask;
    class Include {
    }
    storyboard.Include = Include;
})(storyboard || (storyboard = {}));
