var storyboard;
(function (storyboard) {
    class ViewLayoutGuide {
        getClassName() { return storyboard.ViewLayoutGuide.classname; }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    ViewLayoutGuide.classname = "storyboard.ViewLayoutGuide ";
    storyboard.ViewLayoutGuide = ViewLayoutGuide;
})(storyboard || (storyboard = {}));
