//{INSERTORDER:2}
var seven;
(function (seven) {
    class Color {
        getClassName() { return seven.Color.classname; }
        ///AutoGeneratedClassName-end - do not eidt this line
        static transparent() {
            return "rgba(0,0,0,0.0)";
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Color.classname = "seven.Color ";
    seven.Color = Color;
})(seven || (seven = {}));
