var seven;
(function (seven) {
    class Objects {
        getClassName() { return seven.Objects.classname; }
        ///AutoGeneratedClassName-end - do not eidt this line
        Objects() {
        }
        static requireNonNull(message, object) {
            if (object == undefined || object == null) {
                throw new Error(message);
            }
            return object;
        }
        static requireNumber(message, object) {
            Objects.requireNonNull(message, object);
            if (typeof object == "string") {
                object = parseInt(object);
            }
            Objects.requireNonNull(message, object);
            if (typeof object != "number") {
                throw new Error(message);
            }
            return object;
        }
        static orElse(object, replacement) {
            if (object != undefined && object != null) {
                return object;
            }
            return replacement;
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Objects.classname = "seven.Objects ";
    seven.Objects = Objects;
})(seven || (seven = {}));
