var seven;
(function (seven) {
    class Timer {
        constructor() {
            ///AutoGeneratedClassName-end - do not eidt this line
            this.timeoutTimer = undefined;
        }
        getClassName() { return seven.Timer.classname; }
        timeout(time, callback) {
            this.timeoutCallback = callback;
            this.stop();
            var that = this;
            this.timeoutTimer = setTimeout(function () {
                that.timeoutCalled();
            }, time);
        }
        timeoutCalled() {
            console.log("called");
            this.stop();
            this.timeoutCallback.call();
        }
        interval(time, cllback) { }
        stop() {
            clearTimeout(this.timeoutTimer);
            this.timeoutTimer = undefined;
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Timer.classname = "seven.Timer";
    seven.Timer = Timer;
})(seven || (seven = {}));
