var seven;
(function (seven) {
    class ViewUtility {
        ///AutoGeneratedClassName-end - do not eidt this line
        constructor() {
        }
        getClassName() { return seven.ViewUtility.classname; }
        static randomColor() {
            return '#' + this.hex(this.rg(1, 10)) + this.hex(this.rg(1, 10)) + this.hex(this.rg(1, 15)) +
                this.hex(this.rg(1, 15)) + this.hex(this.rg(1, 15)) + this.hex(this.rg(1, 15));
        }
        static rg(m, n) {
            return Math.floor(Math.random() * (n - m + 1)) + m;
        }
        static hex(i) {
            return i.toString(16);
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    ViewUtility.classname = "seven.ViewUtility ";
    seven.ViewUtility = ViewUtility;
})(seven || (seven = {}));
