namespace storyboard{
    export class Renderer implements seven.IRenderer{
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.Renderer";
		public getClassName():string{return Renderer.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        renderViewHierachy(superView: seven.View) {
           
        }

    }
}