namespace storyboard{
    export class StoryboardSideAdapter{
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "storyboard.StoryboardSideAdapter";
		public getClassName():string{return StoryboardSideAdapter.classname;}
		//AutoGeneratedClassName-end - do not eidt this line
        document:Document;
        scenes:Array<Scene> = new Array<Scene>();

       
    }
}