//auto-generated
namespace storyboard{ 
var storyboardXmlText:string = '';
storyboardXmlText += '<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="14113" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitCollections="YES" useSafeAreas="YES" colorMatched="YES" initialViewController="BYZ-38-t0r">';
storyboardXmlText += '    <device id="ipad9_7" orientation="portrait">';
storyboardXmlText += '        <adaptation id="fullscreen"/>';
storyboardXmlText += '    </device>';
storyboardXmlText += '    <dependencies>';
storyboardXmlText += '        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="14088"/>';
storyboardXmlText += '        <capability name="Constraints with non-1.0 multipliers" minToolsVersion="5.1"/>';
storyboardXmlText += '        <capability name="Safe area layout guides" minToolsVersion="9.0"/>';
storyboardXmlText += '        <capability name="documents saved in the Xcode 8 format" minToolsVersion="8.0"/>';
storyboardXmlText += '    </dependencies>';
storyboardXmlText += '    <scenes>';
storyboardXmlText += '        <!--View Controller-->';
storyboardXmlText += '        <scene sceneID="tne-QT-ifu">';
storyboardXmlText += '            <objects>';
storyboardXmlText += '                <viewController id="BYZ-38-t0r" customClass="ViewController" customModule="test" customModuleProvider="target" sceneMemberID="viewController">';
storyboardXmlText += '                    <view key="view" contentMode="scaleToFill" id="8bC-Xf-vdC">';
storyboardXmlText += '                        <rect key="frame" x="0.0" y="0.0" width="768" height="1024"/>';
storyboardXmlText += '                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>';
storyboardXmlText += '                        <subviews>';
storyboardXmlText += '                            <textField opaque="NO" contentMode="scaleToFill" contentHorizontalAlignment="left" contentVerticalAlignment="center" text="Test" borderStyle="roundedRect" textAlignment="natural" minimumFontSize="17" translatesAutoresizingMaskIntoConstraints="NO" id="Uo6-iX-Fmb">';
storyboardXmlText += '                                <rect key="frame" x="620" y="51" width="49" height="30"/>';
storyboardXmlText += '                                <nil key="textColor"/>';
storyboardXmlText += '                                <fontDescription key="fontDescription" type="system" pointSize="14"/>';
storyboardXmlText += '                                <textInputTraits key="textInputTraits"/>';
storyboardXmlText += '                            </textField>';
storyboardXmlText += '                            <segmentedControl opaque="NO" contentMode="scaleToFill" fixedFrame="YES" contentHorizontalAlignment="left" contentVerticalAlignment="top" segmentControlStyle="plain" selectedSegmentIndex="0" translatesAutoresizingMaskIntoConstraints="NO" id="V4p-7H-n0C">';
storyboardXmlText += '                                <rect key="frame" x="638" y="159" width="121" height="28"/>';
storyboardXmlText += '                                <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>';
storyboardXmlText += '                                <segments>';
storyboardXmlText += '                                    <segment title="First"/>';
storyboardXmlText += '                                    <segment title="Second"/>';
storyboardXmlText += '                                </segments>';
storyboardXmlText += '                            </segmentedControl>';
storyboardXmlText += '                            <progressView opaque="NO" contentMode="scaleToFill" verticalHuggingPriority="750" fixedFrame="YES" progress="0.5" translatesAutoresizingMaskIntoConstraints="NO" id="dg5-jH-oo2">';
storyboardXmlText += '                                <rect key="frame" x="269" y="159" width="150" height="2"/>';
storyboardXmlText += '                                <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>';
storyboardXmlText += '                            </progressView>';
storyboardXmlText += '                            <slider opaque="NO" contentMode="scaleToFill" misplaced="YES" contentHorizontalAlignment="center" contentVerticalAlignment="center" value="0.5" minValue="0.0" maxValue="1" translatesAutoresizingMaskIntoConstraints="NO" id="tEt-Yc-7Uq">';
storyboardXmlText += '                                <rect key="frame" x="32" y="42" width="294" height="31"/>';
storyboardXmlText += '                                <color key="backgroundColor" red="0.26261848523090658" green="1" blue="0.18609234896960014" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>';
storyboardXmlText += '                                <variation key="heightClass=regular-widthClass=regular">';
storyboardXmlText += '                                    <color key="backgroundColor" red="1" green="0.47461094024271921" blue="0.41696197031452553" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>';
storyboardXmlText += '                                </variation>';
storyboardXmlText += '                            </slider>';
storyboardXmlText += '                            <activityIndicatorView opaque="NO" contentMode="scaleToFill" horizontalHuggingPriority="750" verticalHuggingPriority="750" fixedFrame="YES" style="gray" translatesAutoresizingMaskIntoConstraints="NO" id="kca-bd-RGh">';
storyboardXmlText += '                                <rect key="frame" x="407" y="352" width="20" height="20"/>';
storyboardXmlText += '                                <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMaxY="YES"/>';
storyboardXmlText += '                            </activityIndicatorView>';
storyboardXmlText += '                        </subviews>';
storyboardXmlText += '                        ';
storyboardXmlText += '                        <color key="backgroundColor" red="1" green="1" blue="1" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>';
storyboardXmlText += '                        <constraints>';
storyboardXmlText += '                            <constraint firstItem="tEt-Yc-7Uq" firstAttribute="leading" secondItem="6Tk-OE-BBY" secondAttribute="leading" constant="34" id="MSB-G0-enS"/>';
storyboardXmlText += '                            <constraint firstItem="tEt-Yc-7Uq" firstAttribute="top" secondItem="6Tk-OE-BBY" secondAttribute="top" multiplier="0.5" constant="32" id="R6Z-hi-hQW"/>';
storyboardXmlText += '                            <constraint firstItem="6Tk-OE-BBY" firstAttribute="trailing" secondItem="Uo6-iX-Fmb" secondAttribute="trailing" constant="99" id="Yzb-PS-Bnl"/>';
storyboardXmlText += '                            <constraint firstItem="Uo6-iX-Fmb" firstAttribute="top" secondItem="6Tk-OE-BBY" secondAttribute="top" constant="31" id="loG-r0-1Jx"/>';
storyboardXmlText += '                            <constraint firstItem="Uo6-iX-Fmb" firstAttribute="leading" secondItem="tEt-Yc-7Uq" secondAttribute="trailing" constant="71" id="n12-Ad-Ug7"/>';
storyboardXmlText += '                        </constraints>';
storyboardXmlText += '                        <viewLayoutGuide key="safeArea" id="6Tk-OE-BBY"/>';
storyboardXmlText += '                        <variation key="default">';
storyboardXmlText += '                            <mask key="subviews">';
storyboardXmlText += '                                <exclude reference="kca-bd-RGh"/>';
storyboardXmlText += '                            </mask>';
storyboardXmlText += '                        </variation>';
storyboardXmlText += '                        <variation key="heightClass=regular">';
storyboardXmlText += '                            <mask key="subviews">';
storyboardXmlText += '                                <include reference="kca-bd-RGh"/>';
storyboardXmlText += '                            </mask>';
storyboardXmlText += '                        </variation>';
storyboardXmlText += '                    </view>';
storyboardXmlText += '                </viewController>';
storyboardXmlText += '                <placeholder placeholderIdentifier="IBFirstResponder" id="dkx-z0-nzr" sceneMemberID="firstResponder"/>';
storyboardXmlText += '            </objects>';
storyboardXmlText += '            <point key="canvasLocation" x="135.97122302158274" y="126.79856115107914"/>';
storyboardXmlText += '        </scene>';
storyboardXmlText += '    </scenes>';
storyboardXmlText += '</document>';
var parser = new DOMParser();
export var storyboardXml:XMLDocument = parser.parseFromString(storyboardXmlText,"text/xml");
} 
