var seven;
(function (seven) {
    class ImageLoadedCallback {
        constructor(thisRef, method) {
            this.thisRef = thisRef;
            this.method = method;
        }
        getClassName() { return seven.ImageLoadedCallback.classname; }
        call(image) {
            this.method.call(this.thisRef, image);
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    ImageLoadedCallback.classname = "seven.ImageLoadedCallback ";
    seven.ImageLoadedCallback = ImageLoadedCallback;
})(seven || (seven = {}));
