var seven;
(function (seven) {
    class UserAgent {
        getClassName() { return seven.UserAgent.classname; }
        static userAgent() {
            if (UserAgent._instance == undefined) {
                UserAgent._instance = new seven.ClassLoader();
            }
            return UserAgent._instance;
        }
        hasTouchScreen() {
            return (('ontouchstart' in window) || (navigator.msMaxTouchPoints > 0));
        }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    UserAgent.classname = "seven.UserAgent ";
    seven.UserAgent = UserAgent;
})(seven || (seven = {}));
