var storyboard;
(function (storyboard) {
    class Constraint {
        getClassName() { return storyboard.Constraint.classname; }
    }
    //AutoGeneratedClassName-start - do not eidt this line
    Constraint.classname = "storyboard.Constraint ";
    storyboard.Constraint = Constraint;
})(storyboard || (storyboard = {}));
