//{INSERTORDER:3}
/** 
 * the view of the JBDocument
 * all windowViews are attached to here
*/
namespace seven {
    export class DocumentView extends View{
		//AutoGeneratedClassName-start - do not eidt this line
		public static classname:string = "seven.DocumentView";
		public getClassName():string{return DocumentView.classname;}
		//AutoGeneratedClassName-end - do not eidt this line

    constructor(){
        super()
    }
    get rect(){
        return this.frame;
    }
    getZIndex(){
        return 0;
    }
   //@override
    draw(){
        throw new Error("this view cannot be drawn. this should only be used for sizing the subviews");
    }
}
}